mydjango/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.list),
    url(r'^(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^edit/(?P<article_id>[0-9]+)/', views.edit, name='edit'),
    url(r'^edit_action/$', views.edit_action, name='edit_action'),
]

mydjango/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

mydjango/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=32, default='title')
    content = models.TextField(null=True)
    post_time = models.DateTimeField(null=True)

    # def __unicode__(self):
    #     return self.title

mydjango/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from . import models


# Create your views here.
def list(request):
    # return HttpResponse('hello world')
    # return render(request, 'blog/list.html', {'hello': 'hello,mydjango'})
    # article = models.Article.objects.get(pk=1)
    # return render(request, 'blog/list.html', {'hello': 'hello，mydjango', 'article': article})
    articles = models.Article.objects.all()
    return render(request, 'blog/list.html', {'articles': articles})


def detail(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/detail.html', {'article': article})


def edit(request, article_id):
    if article_id == '0':
        return render(request, 'blog/edit.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit.html', {'article': article})


def edit_action(request):
    id = request.POST['id']
    title = request.POST['title']
    content = request.POST['content']
    if id == '':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/list.html', {'articles': articles})

    article = models.Article.objects.get(pk=id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/detail.html', {'article': article})

mydjango/blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>Django detail</title>
</head>
<body>

<h2>{{ article.title }}</h2>
<h3>{{ article.content }}</h3>
<br>
<a href="{% url 'blog:edit' article.id %}">修改文章</a>

</body>
</html>

mydjango/blog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>Django edit</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{ article.id }}">
    标题：<input type="text" name="title" value="{{ article.title }}"><br>
    内容：<input type="text" name="content" value="{{ article.content }}"><br>
    <input type="submit" value="提交">
</form>
</body>
</html>

mydjango/blog/templates/blog/list.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>Django list</title>
</head>
<body>
{#<h1>hello，blog !</h1>#}
{#<h2>{{ hello }}</h2>#}
{#<h3>{{ article.title }}，{{ article.content }}</h3>#}

<h2><a href="{% url 'blog:edit' 0 %}">新文章</a></h2>
<br>
{% for article in articles %}
    <a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a><br>
{% endfor %}
</body>
</html>